# Change these first
owner: Trade-EC # Your GitHub organization or username, where this repository lives
repo: masivo-uptime # The name of this repository

sites:
  - name: App
    url: https://app.masivo.ai/auth/signin
  - name: Docs
    url: https://docs.masivo.ai/overview
  - name: Marketing
    url: https://www.masivo.ai/
  - name: API
    url: app.masivo.ai
    port: 443
    check: "tcp-ping"

assignees:
  - luanlucho
  - Emanuel-Manrique

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /masivo-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Masivo uptime
  introTitle: "**Massivo uptime** use the open-source uptime repo to monitor masivo, powered entirely by GitHub."
  introMessage: On this page you can find all the information regarding Masivo product.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
