# Change these first
owner: Trade-EC # Your GitHub organization or username, where this repository lives
repo: masivo-uptime # The name of this repository

sites:
  - name: App
    url: https://app.masivo.ai/auth/signin
  - name: Docs
    url: https://docs.masivo.ai/overview
  - name: Marketing
    url: https://www.masivo.ai/
  - name: API
    url: https://app.masivo.ai/api/storefront/v1/auth/authorize
    expectedStatusCodes: 
    - 422
    

assignees:
  - luanlucho
  - Emanuel-Manrique

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.masivo.ai
  # baseUrl: /masivo-uptime
  favicon: https://app.masivo.ai/favicon.ico
  logoUrl: https://app.masivo.ai/assets/images/logo.svg
  name: Masivo uptime
  introTitle: "**Masivo uptime**"
  themeUrl: https://trade-ec.github.io/masivo-uptime/main.css
  introMessage: Check the availability of all Masivo services.
  navbar:
    - title: Status
      href: /
      title: App
      href: https://app.masivo.ai


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
